# m1f Auto-Bundle Configuration

# Global settings
global:
  # Exclusions that apply to all bundles
  global_excludes:
    - "**/*.pyc"
    - "**/*.log"
    - "**/tmp/**"
    - "**/dev/**"
    - "**/tests/**/source/**"  # Test input data
    - "**/tests/**/output/**"  # Test output data
    - "**/tests/**/expected/**"  # Expected test results
    - "**/tests/**/scraped_examples/**"  # Scraped test examples

  global_settings:
    # Default security setting for all files
    security_check: "warn"  # Strict by default
    # Use .gitignore as exclude file (can be single file or list)
    exclude_paths_file:
      - ".gitignore"
      - ".m1fignore"
    # Example of multiple exclude files:
    # exclude_paths_file:
    #   - ".gitignore"
    #   - ".m1fignore"

    # Per-extension overrides
    extensions:
      .py:
        security_check: "abort"  # Strict for Python

  # Default settings for all bundles
  defaults:
    force_overwrite: true
    max_file_size: "1MB"
    minimal_output: false
    
  # File watcher settings
  watcher:
    enabled: true
    debounce_seconds: 2
    ignored_paths:
      - ".m1f/"
      - ".git/"
      - ".venv/"
      - "tmp/"
      - ".scrapes/"
      # Note: global_excludes are automatically added to ignored_paths

# Bundle definitions
bundles:
  # Documentation bundles
  all-docs:
    description: "m1f documentation"
    group: "documentation"
    output: ".m1f/m1f-doc/99_m1fdocs.txt"
    sources:
      - path: "."
        include_extensions: [".md", ".txt", ".json", ".yml", ".yaml"]
        excludes: ["tests/**"]
    exclude_paths_file:
      - ".gitignore"
      - ".m1fignore"

  m1f-docs:
    description: "m1f docs"
    group: "documentation"
    output: ".m1f/m1f/55_m1f_docs.txt"
    sources:
      - path: "docs/01_m1f"
        include_extensions: [".md"]

  html2md-docs:
    description: "html2md docs"
    group: "documentation"
    output: ".m1f/m1f/66_html2md_docs.txt"
    sources:
      - path: "docs/03_html2md"
        include_extensions: [".md"]

  scraper-docs:
    description: "m1f-scrape docs"
    group: "documentation"
    output: ".m1f/m1f/77_scraper_docs.txt"
    sources:
      - path: "docs/04_scrape"
        include_extensions: [".md"]

  # Source code bundles
  m1f-code:
    description: "m1f complete code"
    group: "source"
    output: ".m1f/m1f/96_m1f_complete_tool_code.txt"
    sources:
      - path: "tools/m1f"
        include_extensions: [".py"]
      - path: "tools/"
        include_files: [
          "m1f.py",
          "path_utils",
          "__init__.py"
        ]

  s1f-code:
    description: "s1f complete code"
    group: "source"
    output: ".m1f/m1f/96_s1f_complete_tool_code.txt"
    sources:
      - path: "tools/s1f"
        include_files: [
          "s1f.py",
          "path_utils",
          "__init__.py" ]
      - path: "tools/s1f"
        include_extensions: [".py"]

  html2md-code:
    description: "html2md complete code"
    group: "source"
    output: ".m1f/m1f/67_html2md_tool_code.txt"
    sources:
      - path: "tools/html2md_tool"
        include_extensions: [".py"]
      - path: "tools/"
        include_files: [
          "html2md.py",
          "path_utils",
          "__init__.py"
        ]

  scraper-code:
    description: "m1f-scrape complete code"
    group: "source"
    output: ".m1f/m1f/78_scraper_tool_code.txt"
    sources:
      - path: "tools/scrape_tool"
        include_extensions: [".py"]
      - path: "tools/"
        include_files: [
          "scrape.py",
          "path_utils",
          "__init__.py"
        ]
        
  tool-code:
    description: "m1f complete tool code"
    group: "source"
    output: ".m1f/m1f/97_m1f_complete_tool_code.txt"
    sources:
      - path: "tools/"
        include_extensions: [".py"]
    exclude_paths_file:
      - ".gitignore"
      - ".m1fignore"
    
  # Complete project bundle
  all:
    description: "All non-binary files"
    group: "complete"
    output: ".m1f/m1f/98_m1f_allinone.txt"
    sources:
      - path: "."
    exclude_paths_file:
      - ".gitignore"
      - ".m1fignore"
        