# m1f Auto-Bundle Configuration

# Global settings
global:
  # Exclusions that apply to all bundles
  global_excludes:
    - "**/*.pyc"
    - "**/*.log"
    - "**/htmlcov/**"
    - "**/tmp/**"
    - "**/dev/**"
    - "**/tests/**/source/**"  # Test input data
    - "**/tests/**/output/**"  # Test output data
    - "**/tests/**/expected/**"  # Expected test results
    - "**/tests/**/scraped_examples/**"  # Scraped test examples

  global_settings:
    # Default security setting for all files
    security_check: "warn"  # Strict by default

    # Per-extension overrides
    extensions:
      .py:
        security_check: "abort"  # Strict for Python

  # Default settings for all bundles
  defaults:
    force_overwrite: true
    max_file_size: "1MB"
    minimal_output: false
    
  # File watcher settings
  watcher:
    enabled: true
    debounce_seconds: 2
    ignored_paths:
      - ".m1f/"
      - ".git/"
      - ".venv/"
      - "tmp/"
      - "htmlcov/"
      # Note: global_excludes are automatically added to ignored_paths

# Bundle definitions
bundles:
  # Documentation bundle - all markdown files
  all-docs:
    description: "All documentation files"
    output: ".m1f/m1f/99_allm1f_docs.txt"
    sources:
      - path: "."
        include_extensions: [".md", ".txt", ".json"]
        excludes: ["tests/**"]
    preset: "presets/docs-bundle.m1f-presets.yml"

  m1f-docs:
    description: "m1f docs"
    output: ".m1f/m1f/55_m1f_docs.txt"
    sources:
      - path: "docs/01_m1f"
        include_extensions: [".md"]
    preset: "presets/docs-bundle.m1f-presets.yml"

  m1f-code:
    description: "m1f complete code"
    output: ".m1f/m1f/96_m1f_complete_tool_code.txt"
    sources:
      - path: "tools/m1f"
        include_extensions: [".py"]
      - path: "tools/"
        include_files: [
          "m1f.py",
          "path_utils",
          "__init__.py"
        ]

  s1f-code:
    description: "m1f complete code"
    output: ".m1f/m1f/96_s1f_complete_tool_code.txt"
    sources:
      - path: "tools/s1f"
        include_files: [
          - "s1f.py",
          - "path_utils",
          - "__init__.py" ]
      - path: "tools/s1f"
        include_extensions: [".py"]

  tool-code:
    description: "m1f complete tool code"
    output: ".m1f/m1f/97_m1f_complete_tool_code.txt"
    sources:
      - path: "tools/"
        include_extensions: [".py"]
    
  # All non-binary files excluding tests
  all:
    description: "All non-binary files"
    output: ".m1f/m1f/98_mf1_allinone.txt"
    sources:
      - path: "."
        # Only extensions that actually exist in the project
        include_extensions: [
          ".py", ".txt", ".md", ".json", ".js", ".yml", ".yaml",
          ".sh", ".toml", ".ps1", ".example"
        ]
        excludes: [
          ".gitignore"
        ]