# m1f Auto-Bundle Configuration

# Global settings
global:
  # Exclusions that apply to all bundles
  global_excludes:
    - "**/.git/**"
    - "**/.venv/**"
    - "**/node_modules/**"
    - "**/__pycache__/**"
    - "**/*.pyc"
    - "**/.*"  # Hidden files
    - "**/*.log"
    - "**/htmlcov/**"
    - "**/tmp/**"
    
  # Default settings for all bundles
  defaults:
    force_overwrite: true
    max_file_size: "5MB"  # Reduced from 10MB
    minimal_output: false  # Generate file lists
    
  # File watcher settings
  watcher:
    enabled: true
    debounce_seconds: 2
    ignored_paths:
      - ".m1f/"
      - ".git/"
      - ".venv/"
      - "tmp/"
      - "htmlcov/"

# Bundle definitions
bundles:
  # Documentation bundle - all markdown files
  all-docs:
    description: "All markdown documentation files"
    output: ".m1f/docs/99_allm1f_docs.txt"
    sources:
      - path: "."
        include_extensions: [".md"]
        excludes: ["tests/**"]
    preset: "presets/docs-bundle.m1f-presets.yml"

  m1f-docs:
    description: "m1f docs"
    output: ".m1f/m1f/66_m1f_docs.txt"
    sources:
      - path: "."
        include_extensions: [".md"]
        excludes: ["tests/**"]
    preset: "presets/docs-bundle.m1f-presets.yml"