# HTML to Markdown Converter Configuration Example
# This file demonstrates all available configuration options

# Input/Output settings
source: ./html_docs
destination: ./markdown_docs
output_format: markdown  # Options: markdown, m1f_bundle, json

# File handling
file_extensions:
  - .html
  - .htm
  - .xhtml
exclude_patterns:
  - "**/test/**"
  - "**/*.draft.html"
force_overwrite: false

# Encoding
source_encoding: null  # Auto-detect if null
target_encoding: utf-8

# Content extraction settings
extractor:
  # CSS selector for main content area
  content_selector: "article.main-content"
  
  # CSS selectors for elements to ignore
  ignore_selectors:
    - nav
    - .sidebar
    - .advertisement
    - footer
  
  # HTML elements to remove completely
  remove_elements:
    - script
    - style
    - iframe
    - noscript
  
  # HTML elements to preserve as-is
  preserve_elements: []
  
  # Attribute handling
  strip_attributes: true
  preserve_attributes:
    - id
    - href
    - src
    - alt
    - title
  
  # Metadata extraction
  extract_metadata: true
  extract_opengraph: true
  extract_schema_org: true

# Post-processing settings
processor:
  # Text processing
  normalize_whitespace: true
  fix_encoding: true
  
  # Markdown formatting
  heading_offset: 0  # Adjust heading levels (e.g., h1 -> h2 if offset=1)
  heading_style: atx  # Options: atx (# Heading), setext (Heading\n====)
  
  # Code blocks
  code_block_style: fenced  # Options: fenced, indented
  detect_language: true
  
  # Links
  link_handling: convert  # Options: preserve, convert, absolute, relative
  link_extensions:
    .html: .md
    .htm: .md
  
  # Lists
  unordered_list_style: "-"  # Options: -, *, +
  
  # Line breaks
  line_breaks_between_blocks: true

# Web crawling settings (for website conversion)
crawler:
  # Crawling behavior
  follow_links: true
  max_depth: 5
  max_pages: 1000
  
  # URL handling
  allowed_domains:
    - example.com
    - docs.example.com
  url_patterns:
    - "^https://example.com/docs/"
  exclude_patterns:
    - ".*/print$"
    - ".*/api/.*"
  
  # Sitemap
  use_sitemap: true
  sitemap_urls:
    - https://example.com/sitemap.xml
  
  # robots.txt
  respect_robots_txt: true
  
  # Performance
  concurrent_requests: 5
  request_delay: 0.1  # seconds
  timeout: 30.0  # seconds
  
  # User agent
  user_agent: "html_to_md/2.0 (https://github.com/franzundfraz/m1f)"

# Asset handling
assets:
  download_assets: true
  asset_types:
    - image
    - video
    - audio
  asset_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .webp
    - .svg
    - .mp4
    - .webm
    - .mp3
    - .wav
  max_asset_size: 10485760  # 10MB in bytes
  asset_dir: assets

# m1f integration
m1f:
  create_bundle: false
  bundle_name: my-docs
  chunk_size: null  # Auto-determine
  include_assets: true
  generate_index: true
  metadata:
    project: My Documentation
    version: 1.0.0
    author: Your Name

# Processing options
parallel: true
max_workers: null  # Use all CPU cores

# Logging
verbose: false
quiet: false
log_file: null  # Set to a path to enable file logging 