# HTTrack scraper configuration example
scraper_backend: httrack
scraper_config:
  verify_ssl: true
  
crawler:
  max_depth: 10
  max_pages: 1000
  request_delay: 0.2
  concurrent_requests: 8
  respect_robots_txt: true
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  
  # HTTrack-specific settings
  allowed_domains: []  # Empty = same domain only
  excluded_paths:
    - "*/api/*"
    - "*/admin/*"
    - "*.pdf"
    - "*.zip"